<a href="https://colab.research.google.com/github/cantika-alff/2025_PBO_TI1B/blob/main/Jobsheet_AI2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LATIHAN

## Latihan 2

In [8]:
# a. Mendapatkan nilai minimum dan maksimum
x = min(5, 10, 25)
y = max(6, 12, 18)
print("Nilai minimum:", x)
print("Nilai maksimum:", y)

# b. Mendapatkan nilai absolut
x = abs(-7.25)
print("Nilai absolut:", x)

# c. Mendapatkan nilai pangkat
import math
x = math.pow(4, 3)
print("Nilai pangkat 4^3:", x)

# d. Mendapatkan nilai akar
x = math.sqrt(64)
print("Nilai akar dari 64:", x)

# e. Mendapatkan nilai pembulatan
x = math.ceil(1.4)
y = math.floor(1.4)
print("Nilai pembulatan ke atas:", x)
print("Nilai pembulatan ke bawah:", y)

# f. Mendapatkan nilai konstanta (PI)
x = math.pi
print("Nilai konstanta PI:", x)


Nilai minimum: 5
Nilai maksimum: 18
Nilai absolut: 7.25
Nilai pangkat 4^3: 64.0
Nilai akar dari 64: 8.0
Nilai pembulatan ke atas: 2
Nilai pembulatan ke bawah: 1
Nilai konstanta PI: 3.141592653589793


## Latihan 3

In [9]:
import math

# 1. math.sin() - Nilai sinus dari sudut dalam radian
x = math.sin(math.radians(30))  # Konversi 30 derajat ke radian
print("Sinus dari 30 derajat:", x)

# 2. math.cos() - Nilai cosinus dari sudut dalam radian
x = math.cos(math.radians(60))
print("Cosinus dari 60 derajat:", x)

# 3. math.tan() - Nilai tangen dari sudut dalam radian
x = math.tan(math.radians(45))
print("Tangen dari 45 derajat:", x)

# 4. math.log() - Logaritma natural (basis e)
x = math.log(10)
print("Logaritma natural dari 10:", x)

# 5. math.log10() - Logaritma basis 10
x = math.log10(100)
print("Logaritma basis 10 dari 100:", x)

# 6. math.degrees() - Konversi radian ke derajat
x = math.degrees(math.pi)
print("Konversi π radian ke derajat:", x)

# 7. math.dist() - Jarak Euclidean antara dua titik
p1 = (3, 4)
p2 = (6, 8)
x = math.dist(p1, p2)
print("Jarak Euclidean antara (3,4) dan (6,8):", x)

# 8. math.factorial() - Faktorial dari sebuah bilangan
x = math.factorial(5)
print("Faktorial dari 5:", x)

# 9. math.fmod() - Sisa hasil bagi (modulus) dengan desimal
x = math.fmod(10.5, 3)
print("Sisa hasil bagi 10.5 % 3:", x)

# 10. math.isnan() - Mengecek apakah nilai NaN (Not a Number)
x = math.isnan(float('nan'))  # Menghasilkan True
print("Apakah NaN:", x)

# 11. math.gamma() - Fungsi gamma (faktorial untuk bilangan real)
x = math.gamma(6)  # (6-1)! = 5! = 120
print("Gamma dari 6:", x)

# 12. math.perm() - Permutasi dari n dan r
x = math.perm(5, 3)  # P(5,3) = 5! / (5-3)!
print("Permutasi dari 5P3:", x)


Sinus dari 30 derajat: 0.49999999999999994
Cosinus dari 60 derajat: 0.5000000000000001
Tangen dari 45 derajat: 0.9999999999999999
Logaritma natural dari 10: 2.302585092994046
Logaritma basis 10 dari 100: 2.0
Konversi π radian ke derajat: 180.0
Jarak Euclidean antara (3,4) dan (6,8): 5.0
Faktorial dari 5: 120
Sisa hasil bagi 10.5 % 3: 1.5
Apakah NaN: True
Gamma dari 6: 120.0
Permutasi dari 5P3: 60


## Latihan 4

In [13]:
import numpy as np

# Membuat matriks A dan B
A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

# Menjumlahkan matriks
hasil = A + B

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Penjumlahan A + B:\n", hasil)


Matriks A:
 [[80 30 25]
 [50 20 10]]
Matriks B:
 [[30 60 15]
 [10 30 30]]
Hasil Penjumlahan A + B:
 [[110  90  40]
 [ 60  50  40]]


In [15]:
import numpy as np

# Membuat vektor A dan B
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

# Menghitung dot product
hasil = np.dot(A, B)

# Menampilkan hasil
print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil Dot Product:", hasil)


Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil Dot Product: 2025


In [16]:
import numpy as np

# Membuat vektor A dan B
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

# Menghitung cross product
hasil = np.cross(A, B)

# Menampilkan hasil
print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil Cross Product:", hasil)


Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil Cross Product: [-305 -110  350]


# PRAKTIKUM

## Praktikum 1

In [18]:
import numpy as np

# Definisi matriks
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Perkalian matriks A x B
AB = np.dot(A, B)

# Perkalian matriks B x C
BC = np.dot(B, C)

# Menampilkan hasil
print("Hasil A × B:\n", AB)
print("Hasil B × C:\n", BC)


Hasil A × B:
 [[7 2]
 [4 2]]
Hasil B × C:
 [[ 0  2  3]
 [-3  1  3]]


## Praktikum 2

In [20]:
import math

# a. Faktorial 6!
faktorial_6 = math.factorial(6)

# b. Faktorial 8! / 5!
faktorial_8_per_5 = math.factorial(8) / math.factorial(5)

# Menampilkan hasil
print("6! =", faktorial_6)
print("8! / 5! =", faktorial_8_per_5)


6! = 720
8! / 5! = 336.0


## Praktikum 3

In [21]:
import numpy as np

# Definisi vektor dalam format [i, j, k]
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Panjang masing-masing vektor (magnitudo)
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Perkalian titik (dot product)
AB_dot = np.dot(A, B)

# Perkalian silang (cross product)
AB_cross = np.cross(A, B)

# Menampilkan hasil
print("Panjang Vektor A:", panjang_A)
print("Panjang Vektor B:", panjang_B)
print("Perkalian Titik A . B:", AB_dot)
print("Perkalian Silang A × B:\n", AB_cross)


Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Perkalian Titik A . B: 58
Perkalian Silang A × B:
 [ 24  79 -51]
